// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXEK89yg8s5w35JDXxhqfRaU9DwcJQUL8',
    appId: '1:1032353821841:web:232b2f7f69d45648467b30',
    messagingSenderId: '1032353821841',
    projectId: 'shining-d1367',
    authDomain: 'shining-d1367.firebaseapp.com',
    storageBucket: 'shining-d1367.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcsoegiaki7eRyUJNoSNuTWnyyiH6Vh-E',
    appId: '1:1032353821841:android:bc22327cd2f5603c467b30',
    messagingSenderId: '1032353821841',
    projectId: 'shining-d1367',
    storageBucket: 'shining-d1367.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz-OOrOV7E885UPKaxF_J8NxVj7j7KfsA',
    appId: '1:1032353821841:ios:453dc8b07762d934467b30',
    messagingSenderId: '1032353821841',
    projectId: 'shining-d1367',
    storageBucket: 'shining-d1367.firebasestorage.app',
    iosBundleId: 'com.example.shining',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz-OOrOV7E885UPKaxF_J8NxVj7j7KfsA',
    appId: '1:1032353821841:ios:453dc8b07762d934467b30',
    messagingSenderId: '1032353821841',
    projectId: 'shining-d1367',
    storageBucket: 'shining-d1367.firebasestorage.app',
    iosBundleId: 'com.example.shining',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXEK89yg8s5w35JDXxhqfRaU9DwcJQUL8',
    appId: '1:1032353821841:web:b69426462cc65908467b30',
    messagingSenderId: '1032353821841',
    projectId: 'shining-d1367',
    authDomain: 'shining-d1367.firebaseapp.com',
    storageBucket: 'shining-d1367.firebasestorage.app',
  );
}
